### ISSUE TITLE
Unable to do Expert Application

### ISSUE THREAD

**Issue by jasny** [airpair/airpair-com-v1-issue-tracker#251]
When submitting the expert application I get an error:

> Cast to number failed for value "undefined" at path "minRate"

I did fill out the field "Rate on your profile".

![unnamed image](https://cloud.githubusercontent.com/assets/100821/6778735/730dd57e-d155-11e4-89a2-755258f34896.png)

**Comment by jkresner** [comment]
Sorry I've been on vacation :). I found I really annoying issue where mongo wasn't enforcing a unique constraint because of a couple of rogue documents from 12 months ago. I'm not sure if this was the issue, but after quite a bit of data surgery, I've logged in locally as you and was able to complete you profile. Could you please have another crack and let me know if you still cannot continue.

https://www.airpair.com/be-an-expert
