### ISSUE TITLE
Table of Contents not appearing on single post

### ISSUE THREAD

**Issue by dwanderton** [airpair/airpair-com-v1-issue-tracker#253]
I was unable to determine from the markdown why the TOC was not being generated from the headers in this post.

https://www.airpair.com/posts/review/55091bc0e7a0af0c00e06bc5

![screen shot 2015-03-23 at 10 38 49](https://cloud.githubusercontent.com/assets/3466284/6786337/e3def4c0-d148-11e4-9f7f-e0d8042db3c9.png)

**Comment by jkresner** [comment]
Probably something can be fixed with the markdown. Won't look this week.
ᐧ

On Mon, Mar 23, 2015 at 10:39 AM, David Anderton <notifications@github.com>
wrote:

> I was unable to determine from the markdown why the TOC was not being
> generated from the headers in this post.
>
> https://www.airpair.com/posts/review/55091bc0e7a0af0c00e06bc5
>
> [image: screen shot 2015-03-23 at 10 38 49]
> <https://cloud.githubusercontent.com/assets/3466284/6786337/e3def4c0-d148-11e4-9f7f-e0d8042db3c9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/253>.
>



-- 
*Jonathon Kresner*
*Co-founder, CEO*
@AirPair <http://twitter.com/airpair> | *airpair.com
<http://www.airpair.com>*
@hackerpreneur <http://twitter.com/hackerpreneur>
