### ISSUE TITLE
Logging in with google produces error

### ISSUE THREAD

**Issue by ralphcallaway** [airpair/airpair-com-v1-issue-tracker#333]
See https://www.dropbox.com/s/23ldns69ymjqap6/Screenshot%202015-05-19%2012.00.21.png?dl=0

**Comment by jkresner** [comment]
Thanks for flagging this does your email have any caps in it? I'll try get to this later today or tomorrow.

**Comment by ralphcallaway** [comment]
@jkresner tried doing a password reset and it didn't recognize my email as a username, a little confused, i thought i'd signed up a while back but seems like my user disappeared somehow, or i may just have an incorrect username, or maybe i was just suggested an airpair and never completed the setup

i get emails to my gmail account so was surprised when the logging didn't work

**Comment by jkresner** [comment]
Ok, I think I fixed the problem. Can you try google login one more time? Your email started with a capital letter and I've updated it in the db. I've noted the bug. cheers.

**Comment by ralphcallaway** [comment]
oh wild, never noticed that part of my email had a capital in it. nothing like a standard (email case-sensitivity) that it's unexpected to follow

log in works now, thanks

**Comment by jkresner** [comment]
No problem. I'll leave this issue open as a reminder to catch this use case. I think i've coded about 5 others and this was the one that got away.

**Comment by BerndBeekes** [comment]
I have the sample problem!

Google account: bbeekes@googlemail.com (might be "bbeekes@gmail.com".
Could you please check?

Thx /BB

**Comment by jkresner** [comment]
@BerndBeekes are you still having troubles?

![screen shot 2015-05-26 at 10 51 35 am](https://cloud.githubusercontent.com/assets/979542/7819223/0763bb82-0395-11e5-8e43-ce5ae2923c25.png)

**Comment by BerndBeekes** [comment]
Hi Jonathon,

 

I have triesd with different browsers  and on different machines, but always get

 

exception: insertDocument :: caused by :: 11000 E11000 duplicate key error index: 

app33053049.users.$googleId_1 dup key: { : "118001480050780109202" }

 

Thanks for any help!

 

 

Bernd Beekes ( <mailto:berndb@simplexsoftware.de> berndb@simplexsoftware.de)

 

Simplex Software GmbH

Klosterstr. 56, D-51645 Gummersbach

Tel: +49 (0) 2261 959082

Fax: +49 (0) 2261 959083

 <http://www.simplexsoftware.de/> http://www.simplexsoftware.de

 <mailto:berndb@simplexsoftware.de> mailto:info@simplexsoftware.de

 

Sitz der Gesellschaft: Gummersbach

Handelsregister: Amtsgericht Köln HRB 39152

Ust-IdNr.: DE169861972

Steuer-Nr.: 212/5724/0637

Geschäftsführer: Dipl. Math. Bernd Beekes

 

Von: Jonathon Kresner [mailto:notifications@github.com] 
Gesendet: Dienstag, 26. Mai 2015 19:51
An: airpair/airpair-com-v1-issue-tracker
Cc: BerndBeekes
Betreff: Re: [airpair-com-v1-issue-tracker] Logging in with google produces error (#333)

 

@BerndBeekes <https://github.com/BerndBeekes>  are you still having troubles?

 <https://cloud.githubusercontent.com/assets/979542/7819223/0763bb82-0395-11e5-8e43-ce5ae2923c25.png>

**Comment by jkresner** [comment]
Login with github is now the only way to go :)
