### ISSUE TITLE
Discount for open source not applied

### ISSUE THREAD

**Issue by diasks2** [airpair/airpair-com-v1-issue-tracker#54]
Although the $10 discount for open source button was selected this was not applied to the payment.

**Comment by diasks2** [comment]
![airpair_screenshot](https://cloud.githubusercontent.com/assets/1476952/5608027/fb32e916-94b6-11e4-9ce0-06f0566495a8.jpg)

**Comment by jkresner** [comment]
Thanks, looking into this today. Jonathon

On Sun, Jan 4, 2015 at 3:44 PM, Kevin Dias <notifications@github.com> wrote:

> [image: airpair_screenshot]
> <https://cloud.githubusercontent.com/assets/1476952/5608027/fb32e916-94b6-11e4-9ce0-06f0566495a8.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/airpair/airpair-com-v1-issue-tracker/issues/54#issuecomment-68655237>
> .
>



-- 
Jonathon Kresner
about.me <http://about.me/jonathonkresner> | hackerpreneurialism
<http://hackerpreneurialism.com> | @hackerpreneur
<http://twitter.com/hackerpreneur>

**Comment by jkresner** [comment]
@diasks2 thanks for your patience. I wrote a test case that confirmed the issue and have deployed a fix. See you billing page for credit! Also this page is going to change a little bit over the next week as you'll be selecting a time to pair and live chatting in the right rail with experts before you pay instead of HipChat (after you pay).

**Comment by diasks2** [comment]
@jkresner thank you! :thumbsup:
